version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": uvicorn.logging.ColourizedFormatter
    format: '%(asctime)s [%(levelname)8s] : %(message)s'
    use_colors: true
  access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s [%(levelname)8s] : %(message)s'
    use_colors: true
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  fastapi:
    level: INFO
    handlers:
      - default
    propagate: true
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: true
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: true
