[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  | \.eggs
  | \.git
  | \.tox
  | \.venv
  | _build
  | build
  | changelog
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
line_length = 120
known_first_party = []
include_trailing_comma = true
order_by_type = false
skip = [ ".venv" ]
